# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Copy package files
        run: |
          cp server/package.json .
          cp server/package-lock.json .

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> $GITHUB_ENV
        working-directory: server

      - name: Run CI
        run: npm run ci
        working-directory: server

      - name: Build the project
        run: npm run build --if-present
        working-directory: server

      - name: Run tests
        run: npm run test
        working-directory: server

      - name: Clean up package files
        run: |
          rm package.json
          rm package-lock.json
